# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e36087d02f13363223b68c75c9a35ba55605b8a424cce6db021fa6d8fa6753ed843af2fc5f59af427a50637b38b01036bb769ebcab194ae27c69e41a8b9e5827

test:
  secret_key_base: a0f6e87148a43435b195ce562aed76a350e73aa818abb5ccd377a5116f4c7268a5be09c6e9f81cd917f45cffaf549217f47e44aecb4d2ce6bcd7b7e352060183

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
